advancedtelematic/director

- build.sbt
For open source deployment which doesn't use InfluxDB
> Add env variable REPORT_METRICS to be able to turn off metrics

- src/main/scala/com/advancedtelematic/director/http/DeviceResource.scala
- src/main/scala/com/advancedtelematic/director/manifest/Verify.scala
- src/test/scala/com/advancedtelematic/director/data/Generators.scala
- src/test/scala/com/advancedtelematic/director/http/DeviceResourceSpec.scala
- src/test/scala/com/advancedtelematic/director/manifest/VerifySpec.scala
Return error on invalid hash in uploaded manifest
Removed tests for ignoring specific errors.
(Revert of the revert.)
> Return error on invalid hash in uploaded manifest

- build.sbt
- src/main/scala/com/advancedtelematic/director/client/Core.scala
- src/main/scala/com/advancedtelematic/director/daemon/FileCache.scala
- src/main/scala/com/advancedtelematic/director/data/Codecs.scala
- src/main/scala/com/advancedtelematic/director/db/Repository.scala
- src/main/scala/com/advancedtelematic/director/db/Schema.scala
- src/main/scala/com/advancedtelematic/director/roles/RolesGeneration.scala
- src/test/scala/com/advancedtelematic/director/client/FakeKeyserverClient.scala
- src/test/scala/com/advancedtelematic/director/daemon/TufTargetWorkerSpec.scala
- src/test/scala/com/advancedtelematic/director/data/Generators.scala
- src/test/scala/com/advancedtelematic/director/http/AdminResourceSpec.scala
- src/test/scala/com/advancedtelematic/director/http/AutoUpdateSpec.scala
- src/test/scala/com/advancedtelematic/director/http/CancelUpdate.scala
- src/test/scala/com/advancedtelematic/director/http/DeviceRegistrationUtils.scala
- src/test/scala/com/advancedtelematic/director/http/DeviceResourceSpec.scala
- src/test/scala/com/advancedtelematic/director/http/DiffSpec.scala
- src/test/scala/com/advancedtelematic/director/http/FileCacheSpec.scala
- src/test/scala/com/advancedtelematic/director/http/LaunchMultiTargetUpdate.scala
- src/test/scala/com/advancedtelematic/director/http/MultiTargetUpdatesResourceSpec.scala
- src/test/scala/com/advancedtelematic/director/http/NamespacedRequests.scala
- src/test/scala/com/advancedtelematic/director/http/RegisterNamespaceSpec.scala
- src/test/scala/com/advancedtelematic/director/http/Requests.scala
- src/test/scala/com/advancedtelematic/director/http/SetMultiTargetSpec.scala
- src/test/scala/com/advancedtelematic/director/manifest/SignatureVerificationSpec.scala
- src/test/scala/com/advancedtelematic/director/manifest/VerifySpec.scala
- src/test/scala/com/advancedtelematic/director/repo/DirectorRepoSpec.scala
- src/test/scala/com/advancedtelematic/director/util/DirectorSpec.scala
- src/test/scala/com/advancedtelematic/director/util/ResourceSpec.scala
Includes changes cause by bumping libtuf.
> Add Ed25519 tests

- src/main/scala/com/advancedtelematic/director/Boot.scala
- src/main/scala/com/advancedtelematic/director/daemon/DaemonBoot.scala
See https://github.com/advancedtelematic/ota-community-edition/issues/59
> Use InfluxdbMetricsReporterSupport from libats

- build.sbt
- src/test/scala/com/advancedtelematic/director/client/FakeKeyserverClient.scala
- src/test/scala/com/advancedtelematic/director/manifest/VerifySpec.scala
- src/test/scala/com/advancedtelematic/director/repo/DirectorRepoSpec.scala
Also remove some superfluous imports.
> Don't include test libraries in docker images

- build.sbt
- src/main/scala/com/advancedtelematic/director/Boot.scala
- src/main/scala/com/advancedtelematic/director/daemon/DaemonBoot.scala
- src/main/scala/com/advancedtelematic/director/http/DeviceResource.scala
- src/main/scala/com/advancedtelematic/director/manifest/DeviceManifestUpdate.scala
- src/main/scala/com/advancedtelematic/director/manifest/Verify.scala
- src/main/scala/com/advancedtelematic/director/roles/RolesGeneration.scala
- src/test/scala/com/advancedtelematic/director/client/FakeKeyserverClient.scala
- src/test/scala/com/advancedtelematic/director/data/CodecsSpec.scala
- src/test/scala/com/advancedtelematic/director/data/Generators.scala
- src/test/scala/com/advancedtelematic/director/http/DeviceRegistrationUtils.scala
- src/test/scala/com/advancedtelematic/director/http/DeviceResourceSpec.scala
- src/test/scala/com/advancedtelematic/director/http/DiffSpec.scala
- src/test/scala/com/advancedtelematic/director/http/LaunchMultiTargetUpdate.scala
- src/test/scala/com/advancedtelematic/director/http/NamespacedRequests.scala
- src/test/scala/com/advancedtelematic/director/manifest/SignatureVerificationSpec.scala
- src/test/scala/com/advancedtelematic/director/manifest/VerifySpec.scala
- src/test/scala/com/advancedtelematic/director/repo/DirectorRepoSpec.scala
Depends on https://github.com/advancedtelematic/ota-tuf/pull/190
> Use SignedPayload[T] and JsonSignedPayload

- build.sbt
- src/main/scala/com/advancedtelematic/director/Boot.scala
- src/main/scala/com/advancedtelematic/director/daemon/DaemonBoot.scala
> Add prometheus metrics

- src/main/scala/com/advancedtelematic/director/manifest/AfterUpdate.scala
- src/main/scala/com/advancedtelematic/director/manifest/DeviceManifestUpdate.scala
> Refactor manifest,update handling

- docs/swagger.yaml
Moving up-to-date swagger file for director into director repo (instead of "internal docs".
> Adding swagger file (for API documentation)

- build.sbt
- src/main/resources/db/migration/V17__add_correlation_id_fcr.sql
- src/main/scala/com/advancedtelematic/director/daemon/TufTargetWorker.scala
- src/main/scala/com/advancedtelematic/director/data/Codecs.scala
- src/main/scala/com/advancedtelematic/director/data/DataType.scala
- src/main/scala/com/advancedtelematic/director/db/Schema.scala
- src/main/scala/com/advancedtelematic/director/db/SetMultiTargets.scala
- src/main/scala/com/advancedtelematic/director/db/SetTargets.scala
- src/main/scala/com/advancedtelematic/director/http/AdminResource.scala
- src/main/scala/com/advancedtelematic/director/roles/RolesGeneration.scala
- src/test/scala/com/advancedtelematic/director/http/FileCacheSpec.scala
- src/test/scala/com/advancedtelematic/director/http/SetMultiTargetSpec.scala
> Add CorrelationId in TargetsCustom 

- src/main/scala/com/advancedtelematic/director/db/DeviceUpdate.scala
- src/main/scala/com/advancedtelematic/director/manifest/AfterUpdate.scala
- src/main/scala/com/advancedtelematic/director/manifest/DeviceManifestUpdate.scala
Do not use DeviceUpdateReport, OperationResult
> Publish DeviceInstallationReport

- src/main/scala/com/advancedtelematic/director/data/Codecs.scala
- src/main/scala/com/advancedtelematic/director/data/DeviceRequest.scala
- src/main/scala/com/advancedtelematic/director/manifest/AfterUpdate.scala
- src/main/scala/com/advancedtelematic/director/manifest/DeviceManifestUpdate.scala
- src/main/scala/com/advancedtelematic/director/manifest/Verify.scala
- src/test/scala/com/advancedtelematic/director/data/CodecsSpec.scala
- src/test/scala/com/advancedtelematic/director/http/DeviceResourceSpec.scala
- src/test/scala/com/advancedtelematic/director/http/FileCacheSpec.scala
>  Handle InstallationReport in DeviceManifest 

- build.sbt
- src/main/scala/com/advancedtelematic/director/http/DeviceResource.scala
- src/test/scala/com/advancedtelematic/director/http/DeviceResourceSpec.scala
Depends on https://github.com/advancedtelematic/libats/pull/92
> Fix return 404 on missing ECU on PUT manifest

- src/main/scala/com/advancedtelematic/director/manifest/AfterUpdate.scala
> Fix clear next version on failure in AfterUpdate

- build.sbt
- src/main/scala/com/advancedtelematic/director/db/CancelUpdate.scala
- src/main/scala/com/advancedtelematic/director/db/SetMultiTargets.scala
- src/main/scala/com/advancedtelematic/director/http/AdminResource.scala
- src/main/scala/com/advancedtelematic/director/http/AssignmentsResource.scala
- src/main/scala/com/advancedtelematic/director/manifest/AfterUpdate.scala
- src/main/scala/com/advancedtelematic/director/manifest/DeviceManifestUpdate.scala
> [OTA-1688] Publish DeviceUpdateEvent

- build.sbt
- src/main/resources/logback.xml
> use libats-logging

- src/main/resources/db/migration/V22__device_update_assignments.sql
- src/main/scala/com/advancedtelematic/director/data/DataType.scala
- src/main/scala/com/advancedtelematic/director/db/CancelUpdate.scala
- src/main/scala/com/advancedtelematic/director/db/DeviceUpdate.scala
- src/main/scala/com/advancedtelematic/director/db/DeviceUpdateAssignmentRepository.scala
- src/main/scala/com/advancedtelematic/director/db/EcuUpdateAssignmentMigration.scala
- src/main/scala/com/advancedtelematic/director/db/EcuUpdateAssignmentRepository.scala
- src/main/scala/com/advancedtelematic/director/db/Repository.scala
- src/main/scala/com/advancedtelematic/director/db/Schema.scala
- src/main/scala/com/advancedtelematic/director/db/SetTargets.scala
- src/main/scala/com/advancedtelematic/director/http/AdminResource.scala
- src/main/scala/com/advancedtelematic/director/http/AssignmentsResource.scala
- src/main/scala/com/advancedtelematic/director/manifest/AfterUpdate.scala
- src/main/scala/com/advancedtelematic/director/manifest/DeviceManifestUpdate.scala
- src/main/scala/com/advancedtelematic/director/roles/Roles.scala
- src/main/scala/db/migration/R__MigrateEcuUpdateTarget.scala
- src/test/scala/com/advancedtelematic/director/db/SetVersion.scala
- src/test/scala/com/advancedtelematic/director/http/AdminResourceSpec.scala
- src/test/scala/com/advancedtelematic/director/http/SetMultiTargetSpec.scala
> [OTA-2551] Move to {Device,Ecu}UpdateAssignment{Repository}

- src/main/resources/db/migration/V23__ecu_id_unique_per_device.sql
- src/main/scala/com/advancedtelematic/director/db/Schema.scala
> [OTA-2551] Make ecu_serial unique per device instead of namespace

- src/main/scala/com/advancedtelematic/director/db/Repository.scala
- src/main/scala/com/advancedtelematic/director/db/SetMultiTargets.scala
> Fix query device_update_assignments by key

- build.sbt
Scan of this branch: https://artifactory.in.here.com/artifactory/here-oss-local/job-results/6207/director-66f56f74fb9d33f99d7d854aa7585fe8b26da70f-2019-06-28-scan-report.html
> Bump libats and libtuf, add metadata

- build.sbt
> Update Alpine version

- src/main/scala/com/advancedtelematic/director/manifest/DeviceManifestUpdate.scala
This would help debug https://saeljira.it.here.com/browse/OTA-2725
> Add more logging when device reports unexpected target

- build.sbt
- project/plugins.sbt
- src/main/scala/com/advancedtelematic/director/Boot.scala
- src/main/scala/com/advancedtelematic/director/daemon/DaemonBoot.scala
Do not publish latest
Bump libats and libtuf
Remove influxdb
> Publish git HEAD tag when publishing docker image

- .gitlab-ci.yml
Signed-off-by: Vitalii Davydiuk <ext-vitalii.davydiuk@here.com>
> OTA-3711: gitlab pipeline for director

- .gitlab-ci.yml
- build.sbt
- deploy/ci_setup.sh
- src/main/scala/com/advancedtelematic/director/Boot.scala
- src/test/scala/com/advancedtelematic/director/client/FakeKeyserverClient.scala
- src/test/scala/com/advancedtelematic/director/repo/DirectorRepoSpec.scala
Adds support for connection count metrics
> Bump libats
